### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by ripa1995** [runtime-machines/rust-template#4]
## Motivations

- Would you like to implement this feature? [y/n] n

## Solution

Rewrite README.md such that it better describe the scope of this template repository.
Also, provide a templated README.md, with project title, section for description, etc.

**Comment by Eliaxie** [comment]
Improved readme and created a template version with the main points to fill:
- https://github.com/runtime-machines/rust-template/blob/main/README.md 
- https://github.com/runtime-machines/rust-template/blob/main/README.template.md
